/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/assets/invactCity.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.city_sample_floor.geometry} material={materials['Material.191']} position={[0, -0.03, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.sidewalk_x4002.geometry} material={materials['Material.192']} position={[86.95, -0.19, 60.18]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.sidewalk_x4003.geometry} material={materials['Material.192']} position={[-104.16, -0.22, -35.6]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.sidewalk_x4005.geometry} material={materials['Material.192']} position={[-76.36, -0.22, -35.6]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.sidewalk_x4006.geometry} material={materials['Material.192']} position={[-76.36, -0.22, -56.38]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.bus_stop.geometry} material={materials['Material.187']} position={[32.63, 0, 9.8]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.bus_stop001.geometry} material={materials['Material.187']} position={[52.18, 0, 16.32]} rotation={[Math.PI / 2, 0, 0.49]} scale={0} />
      <mesh geometry={nodes.sidewalk_x4004.geometry} material={materials['Material.191']} position={[22.26, -0.17, -85.98]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <group position={[-11.29, 18.39, -75.6]} rotation={[1.32, 0.58, 1.87]} scale={0}>
        <mesh geometry={nodes.Cylinder028.geometry} material={materials['Material.213']} />
        <mesh geometry={nodes.Cylinder028_1.geometry} material={materials['Material.214']} />
        <mesh geometry={nodes.Cylinder028_2.geometry} material={materials['Material.216']} />
        <mesh geometry={nodes.Cylinder028_3.geometry} material={materials['Material.217']} />
      </group>
      <mesh geometry={nodes.bush_plant_big_tall_stem.geometry} material={materials['Material.187']} position={[-32.57, 0.11, 0.17]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.path_park_tile_x4.geometry} material={materials['Material.218']} position={[-5.52, -0.01, -21.03]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.path_park_tile_x4004.geometry} material={materials['Material.218']} position={[-24.3, -0.01, -21.03]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.path_park_tile_x4001.geometry} material={materials['Material.218']} position={[49.84, -0.01, -21.03]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.path_park_tile_x4002.geometry} material={materials['Material.218']} position={[68.62, -0.01, -21.03]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.path_park_tile_x4005.geometry} material={materials['Material.218']} position={[31.52, -0.01, -21.03]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.path_park_tile_x4003.geometry} material={materials['Material.218']} position={[13.14, -0.01, -21.03]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.path_park_tile_x4006.geometry} material={materials['Material.218']} position={[13.14, 0.28, -21.03]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.path_park_tile_x4007.geometry} material={materials['Material.218']} position={[13.14, -0.01, -39.95]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.path_park_tile_x4008.geometry} material={materials['Material.218']} position={[13.14, -0.01, -1.1]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.city_sample_houses_1006.geometry} material={materials['Material.189']} position={[-49.76, 1.61, -84.02]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.235']} position={[-4.59, -0.08, -9.28]} scale={0} />
      <group position={[13.3, 9.26, 9.05]} rotation={[Math.PI / 2, 0, 0]} scale={0}>
        <mesh geometry={nodes.Cube024_1.geometry} material={materials['Material.236']} />
        <mesh geometry={nodes.Cube024_2.geometry} material={materials['Material.237']} />
      </group>
      <group position={[13.3, 8.16, 9.05]} rotation={[Math.PI / 2, 0, 0]} scale={0}>
        <mesh geometry={nodes.Cube024_1.geometry} material={materials['Material.236']} />
        <mesh geometry={nodes.Cube024_2.geometry} material={materials['Material.237']} />
      </group>
      <group position={[13.3, 10.68, 9.05]} rotation={[Math.PI / 2, 0, 0]} scale={0}>
        <mesh geometry={nodes.Cube025_1.geometry} material={materials['Material.238']} />
        <mesh geometry={nodes.Cube025_2.geometry} material={materials['Material.239']} />
        <mesh geometry={nodes.Cube025_3.geometry} material={materials['Material.240']} />
      </group>
      <mesh geometry={nodes.Text.geometry} material={materials['Material.241']} position={[6.87, 9.94, 9.51]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.flower_bunch_2_yellow_pot011.geometry} material={materials['Material.230']} position={[7.37, 0, 7.13]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.flower_bunch_2_yellow_pot001.geometry} material={materials['Material.230']} position={[19.54, 0, 7.13]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.flower_bunch_2_yellow_pot002.geometry} material={materials['Material.230']} position={[-29.26, 0, -50.23]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.flower_bunch_2_yellow_pot003.geometry} material={materials['Material.230']} position={[-31.7, 0, -11.26]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.flower_bunch_2_yellow_pot004.geometry} material={materials['Material.230']} position={[19.91, 0, -47.84]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.flower_bunch_2_yellow_pot005.geometry} material={materials['Material.230']} position={[-31.96, 0, -47.57]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.flower_bunch_2_yellow_pot006.geometry} material={materials['Material.230']} position={[74.62, -0.12, -50.28]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.flower_bunch_2_yellow_pot007.geometry} material={materials['Material.230']} position={[-31.81, 0, -32.65]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.flower_bunch_2_yellow_pot008.geometry} material={materials['Material.230']} position={[-29.85, 0, -28.89]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.flower_bunch_2_yellow_pot009.geometry} material={materials['Material.230']} position={[23.38, 0, -50.13]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.flower_bunch_2_yellow_pot010.geometry} material={materials['Material.230']} position={[6.62, 0, -48.36]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.flower_bunch_2_yellow_pot012.geometry} material={materials['Material.230']} position={[2.34, 0, -50.06]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.flower_bunch_2_yellow_pot013.geometry} material={materials['Material.230']} position={[2.79, 0, 8.42]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.flower_bunch_2_yellow_pot014.geometry} material={materials['Material.230']} position={[-29.82, 0, 8.19]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.flower_bunch_2_yellow_pot015.geometry} material={materials['Material.230']} position={[-32.5, 0, 6.15]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.flower_bunch_2_yellow_pot016.geometry} material={materials['Material.230']} position={[-30.08, 0, -12.97]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.flower_bunch_2_yellow_pot017.geometry} material={materials['Material.230']} position={[69.04, 0, 7.93]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.flower_bunch_2_yellow_pot018.geometry} material={materials['Material.230']} position={[71.24, 0, 5.55]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.flower_bunch_2_yellow_pot019.geometry} material={materials['Material.230']} position={[71.53, 0, -9.42]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.flower_bunch_2_yellow_pot020.geometry} material={materials['Material.230']} position={[69.42, 0, -12.49]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.flower_bunch_2_yellow_pot021.geometry} material={materials['Material.230']} position={[69.13, 0, -29.47]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.flower_bunch_2_yellow_pot022.geometry} material={materials['Material.230']} position={[71.33, 0, -31.87]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.flower_bunch_2_yellow_pot023.geometry} material={materials['Material.230']} position={[77.47, 0, -47.5]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.city_sample_houses_1023.geometry} material={materials['Material.189']} position={[-49.76, 1.61, -84.02]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.city_sample_streets005.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.city_sample_houses_1003.geometry} material={materials['Material.003']} position={[-12.17, 4.74, -91.71]} rotation={[Math.PI / 2, 0, 0]} scale={[0.03, 0.04, 0.03]} />
      <mesh geometry={nodes.city_sample_houses_1004.geometry} material={materials['Material.054']} position={[-75.02, 6.85, 51.14]} rotation={[Math.PI / 2, 0, 0]} scale={[0.5, 0.5, 0.58]} />
      <mesh geometry={nodes.city_sample_houses_1002.geometry} material={materials['Material.008']} position={[-74.88, 18.3, 51.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.park_wall_pillar017.geometry} material={materials['Material.086']} position={[7.32, 0.96, 8.89]} rotation={[Math.PI / 2, 0, 0]} scale={[0.02, 0.02, 0.03]} />
      <mesh geometry={nodes.park_wall_pillar004.geometry} material={materials['Material.086']} position={[19.39, 0.96, 8.89]} rotation={[Math.PI / 2, 0, 0]} scale={[0.02, 0.02, 0.03]} />
      <mesh geometry={nodes.park_wall_pillar014.geometry} material={materials['Material.083']} position={[-32.02, 0.54, -27.43]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.park_wall_pillar001.geometry} material={materials['Material.083']} position={[-32.02, 0.54, -14.67]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.park_wall_pillar002.geometry} material={materials['Material.083']} position={[71.17, 0.54, -27.43]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.park_wall_pillar003.geometry} material={materials['Material.083']} position={[71.17, 0.54, -14.67]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.park_wall_pillar005.geometry} material={materials['Material.083']} position={[6.69, 0.54, -50.44]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.02} />
      <mesh geometry={nodes.park_wall_pillar006.geometry} material={materials['Material.083']} position={[19.44, 0.54, -50.44]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.02} />
      <mesh geometry={nodes.city_sample_streets003.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.city_sample_streets006.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.city_sample_houses_1010.geometry} material={materials['Material.008']} position={[-74.88, 18.3, 51.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.city_sample_houses_1042.geometry} material={materials['Material.008']} position={[25.65, 1.18, 8.16]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.02} />
      <mesh geometry={nodes.city_sample_houses_1043.geometry} material={materials['Material.008']} position={[44.36, 1.18, 8.16]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.02} />
      <mesh geometry={nodes.city_sample_houses_1044.geometry} material={materials['Material.008']} position={[63.07, 1.18, 8.16]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.02} />
      <mesh geometry={nodes.city_sample_houses_1015.geometry} material={materials['Material.009']} position={[-31.86, 2.23, 7.91]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.city_sample_houses_1016.geometry} material={materials['Material.009']} position={[-31.86, 2.23, -12.73]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.city_sample_houses_1018.geometry} material={materials['Material.010']} position={[4.79, 0.96, 9.02]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.city_sample_houses_1019.geometry} material={materials['Material.010']} position={[71.04, 0.96, -11.99]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.city_sample_houses_1020.geometry} material={materials['Material.010']} position={[71.15, 0.96, 7.68]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.city_sample_houses_1021.geometry} material={materials['Material.010']} position={[77.03, 0.96, -49.77]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.city_sample_houses_1022.geometry} material={materials['Material.010']} position={[71.09, 0.96, -29.71]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.city_sample_houses_1045.geometry} material={materials['Material.010']} position={[-31.32, 1.52, -30.38]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.city_sample_houses_1012.geometry} material={materials['Material.010']} position={[-31.32, 1.52, -49.48]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.city_sample_houses_1013.geometry} material={materials['Material.010']} position={[6.77, 1.52, -27.62]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.city_sample_houses_1014.geometry} material={materials['Material.010']} position={[6.77, 1.52, -14.28]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.city_sample_houses_1017.geometry} material={materials['Material.010']} position={[19.96, 1.52, -27.62]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.city_sample_houses_1046.geometry} material={materials['Material.010']} position={[19.96, 1.52, -14.28]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.city_sample_houses_1034.geometry} material={materials['Material.010']} position={[21.83, 1.52, -49.48]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.city_sample_houses_1035.geometry} material={materials['Material.010']} position={[4.56, 1.52, -49.48]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.city_sample_streets030.geometry} material={materials['Material.001']} position={[0, 0.62, 9.07]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.city_sample_streets031.geometry} material={materials['Material.001']} position={[-9.31, 1.68, 8.91]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.city_sample_streets032.geometry} material={materials['Material.001']} position={[-110.44, 4.04, 84.6]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.city_sample_houses_1025.geometry} material={materials['Material.010']} position={[-13.05, 0.8, -98.35]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.02} />
      <mesh geometry={nodes.city_sample_houses_1026.geometry} material={materials['Material.010']} position={[-13.05, 1.07, -86.02]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.02} />
      <mesh geometry={nodes['classroom-door'].geometry} material={materials['Material.003']} position={[-24.82, 2.05, -80.28]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.02} />
      <mesh geometry={nodes['classroom-door2'].geometry} material={materials['Material.003']} position={[1.2, 2.05, -80.28]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.02} />
      <group position={[48.18, -0.28, -49.99]} scale={[1.03, 1.03, 1.01]}>
        <mesh geometry={nodes.Icosphere010.geometry} material={materials['Material.235']} />
        <mesh geometry={nodes.Icosphere010_1.geometry} material={materials['Material.043']} />
      </group>
      <group position={[77.91, -0.28, -42.77]} rotation={[0, Math.PI / 2, 0]} scale={[1.03, 1.03, 1.01]}>
        <mesh geometry={nodes.Icosphere010.geometry} material={materials['Material.235']} />
        <mesh geometry={nodes.Icosphere010_1.geometry} material={materials['Material.043']} />
      </group>
      <mesh geometry={nodes.Plane002.geometry} material={materials['default']} position={[-34.37, 0.59, -77.33]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.city_sample_houses_1055.geometry} material={materials['Material.054']} position={[-68.88, 4.05, 9.61]} rotation={[Math.PI / 2, 0, 0]} scale={[0.6, 0.6, 0.71]} />
      <mesh geometry={nodes.city_sample_houses_1054.geometry} material={materials['Material.054']} position={[-90.21, 4.05, 10.07]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.6, 0.6, 0.71]} />
      <mesh geometry={nodes.city_sample_houses_1056.geometry} material={materials['Material.054']} position={[-68.72, 3.39, -23.9]} rotation={[Math.PI / 2, 0, 0]} scale={[0.6, 0.6, 0.71]} />
      <mesh geometry={nodes.city_sample_houses_1057.geometry} material={materials['Material.054']} position={[-90.21, 4.05, -24.17]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.6, 0.6, 0.71]} />
      <mesh geometry={nodes.city_sample_houses_1028.geometry} material={materials['Material.054']} position={[-62.55, 3.5, -53.1]} rotation={[Math.PI / 2, 0, 0]} scale={[0.49, 0.49, 0.58]} />
      <mesh geometry={nodes.city_sample_houses_1047.geometry} material={materials['Material.054']} position={[-62.55, 3.24, -32.3]} rotation={[Math.PI / 2, 0, 0]} scale={[0.49, 0.49, 0.58]} />
      <mesh geometry={nodes.city_sample_houses_1048.geometry} material={materials['Material.054']} position={[-97.01, 3.5, -53.1]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.49, 0.49, 0.58]} />
      <mesh geometry={nodes.city_sample_houses_1049.geometry} material={materials['Material.054']} position={[-97.01, 3.5, -32.55]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.49, 0.49, 0.58]} />
      <mesh geometry={nodes.Cylinder008.geometry} material={materials['White_Plastic.001']} position={[-65.69, 25.48, 54.39]} />
      <group position={[-65.64, 20.71, 54.35]} scale={2.95}>
        <mesh geometry={nodes.Cylinder003_1.geometry} material={materials['Coffee.001']} />
        <mesh geometry={nodes.Cylinder003_2.geometry} material={materials['Material.019']} />
      </group>
      <mesh geometry={nodes.Stirrer.geometry} material={materials['White_Plastic.001']} position={[-65.7, 26.61, 56.55]} rotation={[-1.5, 0.01, -0.01]} scale={0} />
      <group position={[-68.87, 26.75, 43.64]} rotation={[Math.PI / 2, 0, -2.35]} scale={0}>
        <mesh geometry={nodes.Torus002_1.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.Torus002_2.geometry} material={materials['Material.016']} />
        <mesh geometry={nodes['Torus001|Cylinder001|Dupli|001'].geometry} material={materials['Material.018']} position={[97646776, -57407556, -24600378]} rotation={[-3.11, -0.22, 1.67]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder001|Dupli|12001'].geometry} material={materials['Material.018']} position={[-124734152, -50822852, -35447724]} rotation={[-2.92, -0.08, 2.13]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder001|Dupli|16001'].geometry} material={materials['Material.018']} position={[-152766336, -19285252, -29053486]} rotation={[-2.82, 0.03, 2.66]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder001|Dupli|20001'].geometry} material={materials['Material.018']} position={[-157457536, -5391997, 24513298]} rotation={[-3.04, -0.15, 2.92]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder001|Dupli|24001'].geometry} material={materials['Material.018']} position={[-94029312, -30620786, 118757968]} rotation={[2.77, -0.64, 2.39]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder001|Dupli|28001'].geometry} material={materials['Material.018']} position={[-4770687, -52833140, 83402480]} rotation={[-2.77, 0.11, 1.62]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder001|Dupli|32001'].geometry} material={materials['Material.018']} position={[51092484, -51674288, 115668296]} rotation={[2.64, -0.66, 1.45]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder001|Dupli|36001'].geometry} material={materials['Material.018']} position={[95602760, -2213744, 128626592]} rotation={[2.39, -0.77, 1.22]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder001|Dupli|4001'].geometry} material={materials['Material.018']} position={[73453496, -55397132, -85181112]} rotation={[-2.98, -0.06, 1.53]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder001|Dupli|40001'].geometry} material={materials['Material.018']} position={[131820928, -43118204, 43519168]} rotation={[1.96, -0.83, 0.57]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder001|Dupli|44001'].geometry} material={materials['Material.018']} position={[46031176, 22885012, 156824448]} rotation={[1.05, -0.95, 1.08]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder001|Dupli|48001'].geometry} material={materials['Material.018']} position={[156392416, 26246790, 44507192]} rotation={[0.02, -0.3, 0.28]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder001|Dupli|8001'].geometry} material={materials['Material.018']} position={[-44856272, -5391826.5, -152910064]} rotation={[-2.37, 0.36, 1.85]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder002|Dupli|1001'].geometry} material={materials['Material.018']} position={[135919488, -43117892, -28221694]} rotation={[-2.5, 0.47, 0.84]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder002|Dupli|13001'].geometry} material={materials['Material.018']} position={[-131821384, -43117956, -43519020]} rotation={[-2.84, -0.01, 2.31]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder002|Dupli|17001'].geometry} material={materials['Material.018']} position={[-69560072, -46283136, -7525935.5]} rotation={[2.79, -0.42, 0.99]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder002|Dupli|21001'].geometry} material={materials['Material.018']} position={[-80800576, -57407544, 60096148]} rotation={[-3.1, -0.2, 1.63]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder002|Dupli|25001'].geometry} material={materials['Material.018']} position={[-48745340, -19285166, 147667184]} rotation={[2.41, -0.85, 2.13]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder002|Dupli|29001'].geometry} material={materials['Material.018']} position={[-13586812, -51674672, 125718128]} rotation={[2.77, -0.6, 1.72]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder002|Dupli|33001'].geometry} material={materials['Material.018']} position={[73734728, -30621552, 132317672]} rotation={[1.54, -0.97, 0.89]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder002|Dupli|37001'].geometry} material={materials['Material.018']} position={[92400512, -43118260, 103599304]} rotation={[2.02, -0.88, 0.95]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder002|Dupli|41001'].geometry} material={materials['Material.018']} position={[163394432, 22884576, -3874056.75]} rotation={[-0.23, -0.03, 0.17]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder002|Dupli|45001'].geometry} material={materials['Material.018']} position={[127455456, 26246796, 100968152]} rotation={[0.35, -0.61, 0.48]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder002|Dupli|49001'].geometry} material={materials['Material.018']} position={[166962336, 8185089.5, 9528729]} rotation={[-0.11, -0.04, -0.35]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder002|Dupli|5001'].geometry} material={materials['Material.018']} position={[94004912, -5391695.5, -128672128]} rotation={[-2.43, 0.41, 1.25]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder002|Dupli|9001'].geometry} material={materials['Material.018']} position={[-70128776, -57406664, -72264496]} rotation={[-3.14, -0.24, 1.63]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder003|Dupli|10001'].geometry} material={materials['Material.018']} position={[-92400848, -43117772, -103598960]} rotation={[-2.63, 0.18, 2.09]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder003|Dupli|14001'].geometry} material={materials['Material.018']} position={[-148618576, -5391879, -57499312]} rotation={[-2.65, 0.21, 2.77]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder003|Dupli|18001'].geometry} material={materials['Material.018']} position={[-100687240, -57406272, -1510444.13]} rotation={[-3.12, -0.22, 1.62]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder003|Dupli|2001'].geometry} material={materials['Material.018']} position={[143072448, -32947526, -41945856]} rotation={[-1.09, 0.64, 0.01]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder003|Dupli|22001'].geometry} material={materials['Material.018']} position={[-128566592, -19285046, 87478064]} rotation={[2.97, -0.46, 2.61]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder003|Dupli|26001'].geometry} material={materials['Material.018']} position={[-23047358, -56556020, 94723664]} rotation={[-3.03, -0.13, 1.63]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder003|Dupli|30001'].geometry} material={materials['Material.018']} position={[-82482000, -1933842, -148052848]} rotation={[2.99, -0.37, 1.57]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder003|Dupli|34001'].geometry} material={materials['Material.018']} position={[12085703, -701419.75, 163337408]} rotation={[2.89, -0.49, 1.64]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder003|Dupli|38001'].geometry} material={materials['Material.018']} position={[93504576, -32946610, 116129984]} rotation={[1.43, -0.94, 0.66]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder003|Dupli|42001'].geometry} material={materials['Material.018']} position={[157693120, 26246588, -39651976]} rotation={[-0.41, 0.12, 0.35]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder003|Dupli|46001'].geometry} material={materials['Material.018']} position={[126659520, 8185229.5, 109200152]} rotation={[0.84, -0.82, 0.25]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder003|Dupli|6001'].geometry} material={materials['Material.018']} position={[-17486864, -30621010, -150462576]} rotation={[-2.15, 0.47, 1.74]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder004|Dupli|11001'].geometry} material={materials['Material.018']} position={[-37085064, -23609028, -35390068]} rotation={[0.77, -0.81, 0.32]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder004|Dupli|15001'].geometry} material={materials['Material.018']} position={[-128293768, -50823236, -18863466]} rotation={[-2.96, -0.12, 2.14]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder004|Dupli|19001'].geometry} material={materials['Material.018']} position={[-112294728, -55396864, -6419371.5]} rotation={[-3.06, -0.2, 1.84]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder004|Dupli|23001'].geometry} material={materials['Material.018']} position={[-35390724, -23608828, 37084684]} rotation={[-1.3, 0.59, 0.7]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder004|Dupli|27001'].geometry} material={materials['Material.018']} position={[-22051898, -30620910, 149861744]} rotation={[2.33, -0.88, 1.88]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder004|Dupli|3001'].geometry} material={materials['Material.018']} position={[108724720, -30620428, -105468864]} rotation={[-1.64, 0.64, 0.75]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder004|Dupli|31001'].geometry} material={materials['Material.018']} position={[51221700, -19285102, 146826432]} rotation={[1.99, -0.94, 1.25]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder004|Dupli|35001'].geometry} material={materials['Material.018']} position={[77546312, -32947184, 127341352]} rotation={[1.6, -0.96, 0.87]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder004|Dupli|39001'].geometry} material={materials['Material.018']} position={[137548640, -2214709.75, 82249760]} rotation={[2.42, -0.72, 1.03]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder004|Dupli|43001'].geometry} material={materials['Material.018']} position={[138260912, 8185204.5, -94080840]} rotation={[-1.22, 0.61, 0.43]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder004|Dupli|47001'].geometry} material={materials['Material.018']} position={[143440576, 22884938, 78342360]} rotation={[0.23, -0.5, 0.28]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus001|Cylinder004|Dupli|7001'].geometry} material={materials['Material.018']} position={[-28222030, -43117456, -135919920]} rotation={[-2.46, 0.32, 1.78]} scale={[0.02, 0.06, 0.02]} />
      </group>
      <group position={[-68.87, 26.68, 43.64]} rotation={[Math.PI / 2, 0, -2.35]} scale={0}>
        <mesh geometry={nodes.Torus001_1.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.Torus001_2.geometry} material={materials['Material.016']} />
        <mesh geometry={nodes['Torus002|Cylinder001|Dupli|001'].geometry} material={materials['Material.018']} position={[791479.38, -26786438, -52125144]} rotation={[1.91, -0.98, 1.81]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder001|Dupli|12001'].geometry} material={materials['Material.018']} position={[-39167048, 51677752, -70400416]} rotation={[0.32, -0.54, 1.4]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder001|Dupli|16001'].geometry} material={materials['Material.018']} position={[-55414860, 56517368, -81421664]} rotation={[0.13, -0.34, 1.56]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder001|Dupli|20001'].geometry} material={materials['Material.018']} position={[-92516872, 57743352, -67516632]} rotation={[-0.02, -0.14, 1.74]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder001|Dupli|24001'].geometry} material={materials['Material.018']} position={[-111203784, 58644160, -1752441.63]} rotation={[0.04, -0.21, 1.7]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder001|Dupli|28001'].geometry} material={materials['Material.018']} position={[-63068740, 43525252, 31773508]} rotation={[-0.3, 0, 1.07]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder001|Dupli|32001'].geometry} material={materials['Material.018']} position={[-78342584, 22884498, 143441136]} rotation={[2.01, -0.91, 2.54]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder001|Dupli|36001'].geometry} material={materials['Material.018']} position={[-22085632, 51677896, 77475840]} rotation={[-0.41, 0.16, 1.52]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder001|Dupli|4001'].geometry} material={materials['Material.018']} position={[69142968, 43526336, -14367077]} rotation={[0.95, -0.69, 2.63]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder001|Dupli|40001'].geometry} material={materials['Material.018']} position={[20036290, 56517964, 96430016]} rotation={[-0.13, -0.05, 1.68]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder001|Dupli|44001'].geometry} material={materials['Material.018']} position={[133990208, 46874312, 51788248]} rotation={[0.05, -0.34, 1.09]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder001|Dupli|48001'].geometry} material={materials['Material.018']} position={[111203736, 58643520, 1752662.5]} rotation={[0.02, -0.22, 1.6]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder001|Dupli|8001'].geometry} material={materials['Material.018']} position={[33855216, 46874992, -139604192]} rotation={[-0.54, 0.26, 1.5]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder002|Dupli|1001'].geometry} material={materials['Material.018']} position={[-71202872, -701741.56, 147497264]} rotation={[3.08, -0.31, 1.71]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder002|Dupli|13001'].geometry} material={materials['Material.018']} position={[-44312588, 56517620, -87958176]} rotation={[0.15, -0.35, 1.58]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder002|Dupli|17001'].geometry} material={materials['Material.018']} position={[-102542224, 22885232, -127271128]} rotation={[-1.63, 0.65, 2.44]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder002|Dupli|21001'].geometry} material={materials['Material.018']} position={[-106961160, 58644220, -30474394]} rotation={[0.03, -0.2, 1.7]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder002|Dupli|25001'].geometry} material={materials['Material.018']} position={[-121898944, 53804484, 42538152]} rotation={[0.3, -0.38, 2.02]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder002|Dupli|29001'].geometry} material={materials['Material.018']} position={[-139567168, 22884810, 85052592]} rotation={[2.61, -0.6, -3.03]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder002|Dupli|33001'].geometry} material={materials['Material.018']} position={[-56082620, 49335632, 129635520]} rotation={[0.78, -0.76, 1.98]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder002|Dupli|37001'].geometry} material={materials['Material.018']} position={[-28814394, 36113748, 151555456]} rotation={[1.1, -0.9, 1.92]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder002|Dupli|41001'].geometry} material={materials['Material.018']} position={[59636292, 57742988, 97782072]} rotation={[0.1, -0.3, 1.6]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder002|Dupli|45001'].geometry} material={materials['Material.018']} position={[139732928, 49336196, 20619062]} rotation={[-0.03, -0.25, 1.09]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder002|Dupli|49001'].geometry} material={materials['Material.018']} position={[70504888, 43526016, 4017947.25]} rotation={[-0.1, 0.11, 2.33]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder002|Dupli|5001'].geometry} material={materials['Material.018']} position={[104728984, 57743292, -46363176]} rotation={[-0.03, -0.18, 1.55]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder002|Dupli|9001'].geometry} material={materials['Material.018']} position={[-16249999, 49335600, -140308384]} rotation={[-0.56, 0.31, 1.7]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder003|Dupli|10001'].geometry} material={materials['Material.018']} position={[-9539534, 53804592, -128754848]} rotation={[-0.33, 0.13, 1.67]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder003|Dupli|14001'].geometry} material={materials['Material.018']} position={[-24270472, 32764538, -54796444]} rotation={[0.57, -0.75, 1.27]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder003|Dupli|18001'].geometry} material={materials['Material.018']} position={[-113186896, 26246898, -116740312]} rotation={[-1.61, 0.67, 2.54]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder003|Dupli|2001'].geometry} material={materials['Material.018']} position={[26660926, -23608954, 43782664]} rotation={[-2.01, 0.54, 2.36]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder003|Dupli|22001'].geometry} material={materials['Material.018']} position={[-164291008, 8185212.5, -31239952]} rotation={[-2.77, 0.15, 3.02]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder003|Dupli|26001'].geometry} material={materials['Material.018']} position={[-149474688, 22884872, 66107788]} rotation={[2.78, -0.47, -2.91]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder003|Dupli|30001'].geometry} material={materials['Material.018']} position={[-69087296, 58643724, 87156896]} rotation={[0.08, -0.25, 1.69]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder003|Dupli|34001'].geometry} material={materials['Material.018']} position={[-52417080, 8185172, 158807472]} rotation={[2.36, -0.87, 2.16]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder003|Dupli|38001'].geometry} material={materials['Material.018']} position={[-33856060, 46874256, 139604288]} rotation={[0.79, -0.78, 1.87]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder003|Dupli|42001'].geometry} material={materials['Material.018']} position={[28738622, 248837.08, 38689476]} rotation={[-0.34, 0.19, 1.88]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder003|Dupli|46001'].geometry} material={materials['Material.018']} position={[126836352, 53804388, 24110454]} rotation={[0, -0.26, 1.29]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder003|Dupli|6001'].geometry} material={materials['Material.018']} position={[56081712, 49335536, -129635304]} rotation={[-0.45, 0.18, 1.43]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder004|Dupli|11001'].geometry} material={materials['Material.018']} position={[-1173384.38, 3611002.25, -49062428]} rotation={[0.5, -0.64, 1.65]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder004|Dupli|15001'].geometry} material={materials['Material.018']} position={[-66306892, 58644276, -89290592]} rotation={[-0.01, -0.17, 1.68]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder004|Dupli|19001'].geometry} material={materials['Material.018']} position={[-102696656, 36114036, -115120408]} rotation={[-1.14, 0.64, 2.31]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder004|Dupli|23001'].geometry} material={materials['Material.018']} position={[-162502912, 22884734, -17486194]} rotation={[-2.77, 0.27, -2.75]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder004|Dupli|27001'].geometry} material={materials['Material.018']} position={[-123410048, 49335624, 68706248]} rotation={[0.8, -0.69, 2.33]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder004|Dupli|3001'].geometry} material={materials['Material.018']} position={[136986816, 49335548, -34424108]} rotation={[-0.18, -0.11, 1.11]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder004|Dupli|31001'].geometry} material={materials['Material.018']} position={[-54018624, 56517388, 82354784]} rotation={[-0.12, -0.09, 1.56]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder004|Dupli|35001'].geometry} material={materials['Material.018']} position={[-41271036, 57742988, 106838688]} rotation={[0.14, -0.32, 1.7]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder004|Dupli|39001'].geometry} material={materials['Material.018']} position={[16248965, 49335312, 140308672]} rotation={[0.55, -0.69, 1.59]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder004|Dupli|43001'].geometry} material={materials['Material.018']} position={[47013376, 43525128, 52696220]} rotation={[-0.78, 0.51, 2.13]} scale={[0.02, 0.06, 0.02]} />
        <mesh geometry={nodes['Torus002|Cylinder004|Dupli|47001'].geometry} material={materials['Material.018']} position={[47693756, 3610817.75, 11565730]} rotation={[-1.22, 0.75, 2.79]} scale={[0.02, 0.06, 0.02]} />
      </group>
      <mesh geometry={nodes.Circle003.geometry} material={materials['Material.014']} position={[-65.5, 12.4, 3.83]} scale={0.92} />
      <mesh geometry={nodes.Circle004.geometry} material={materials['Material.014']} position={[-65.5, 12.4, -6]} scale={0.92} />
      <mesh geometry={nodes.Circle005.geometry} material={materials['Material.014']} position={[-65.5, 12.4, -16.58]} scale={0.92} />
      <mesh geometry={nodes.city_sample_houses_1065.geometry} material={materials['Material.002']} position={[-79.73, 7.3, 6.24]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.02} />
      <mesh geometry={nodes.city_sample_houses_1058.geometry} material={materials['Material.002']} position={[-79.2, 7.3, -20.02]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.02} />
      <mesh geometry={nodes.city_sample_houses_1064.geometry} material={materials['Material.002']} position={[-72.52, 26.76, -8.27]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.02} />
      <mesh geometry={nodes.city_sample_houses_1063.geometry} material={materials['Material.002']} position={[-72.52, 26.76, 11.89]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.02} />
      <mesh geometry={nodes.city_sample_houses_1062.geometry} material={materials['Material.004']} position={[-85.19, 6.41, 11.41]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.city_sample_houses_1061.geometry} material={materials['Material.004']} position={[-73.82, 6.41, 11.41]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.city_sample_houses_1060.geometry} material={materials['Material.004']} position={[-73.19, 6.41, -25.27]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.city_sample_houses_1059.geometry} material={materials['Material.004']} position={[-84.56, 6.41, -25.27]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.city_sample_houses_1032.geometry} material={materials['Material.011']} position={[-67.72, 3.52, -6.1]} rotation={[Math.PI / 2, 0, 0]} scale={[0.04, 0.03, 0.04]} />
      <mesh geometry={nodes.Cube052.geometry} material={materials['Material.002']} position={[-79.37, 32.54, -3.86]} rotation={[0.32, 0, 0]} scale={8.51} />
      <mesh geometry={nodes.Cube051.geometry} material={materials['Material.002']} position={[-82.75, 38.31, 1.74]} rotation={[0.11, 0, 0]} scale={2.03} />
      <mesh geometry={nodes.Cube050.geometry} material={materials['Material.002']} position={[-76.05, 37.3, 0.59]} rotation={[0.02, -0.13, -0.34]} scale={1.69} />
      <mesh geometry={nodes.Cube029.geometry} material={materials['Material.002']} position={[-79.33, 40.78, -2.23]} rotation={[0.11, 0, 0]} scale={1.75} />
      <mesh geometry={nodes.Cube028.geometry} material={materials['Material.002']} position={[-74.83, 38.5, -4.07]} rotation={[0.11, 0, 0]} scale={1.74} />
      <mesh geometry={nodes.Cube010.geometry} material={materials['Material.002']} position={[-66.23, 15.83, -7.45]} scale={0.95} />
      <mesh geometry={nodes.Cube011.geometry} material={materials['Material.002']} position={[-69.39, 20.19, 7.57]} rotation={[0, -0.64, 0]} scale={0.92} />
      <mesh geometry={nodes.Cube012.geometry} material={materials['Material.002']} position={[-65.26, 22.14, 0.59]} rotation={[0, -0.44, 0]} scale={0.92} />
      <mesh geometry={nodes.Cube013.geometry} material={materials['Material.002']} position={[-63.51, 25.23, -5.98]} rotation={[0, -0.01, 0]} scale={0.92} />
      <mesh geometry={nodes.Cube014.geometry} material={materials['Material.002']} position={[-64.07, 22.14, -13.04]} rotation={[0, 0.13, 0]} scale={0.92} />
      <mesh geometry={nodes.Cube015.geometry} material={materials['Material.002']} position={[-67.17, 20.19, -20.22]} rotation={[Math.PI, -0.74, Math.PI]} scale={0.92} />
      <mesh geometry={nodes.Cube016.geometry} material={materials['Material.002']} position={[-78.78, 6.38, -7.05]} scale={[0.88, 0.92, 0.92]} />
      <mesh geometry={nodes.Cube017.geometry} material={materials['Material.002']} position={[-79.17, 19.86, -6.81]} scale={[11.37, 0.92, 17.89]} />
      <mesh geometry={nodes.Cube018.geometry} material={materials['Material.002']} position={[-68.83, 3.96, -5.51]} scale={0.73} />
      <mesh geometry={nodes.Cube019.geometry} material={materials['Material.002']} position={[-68.83, 3.96, -8.02]} scale={0.73} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials['steel.001']} position={[-63.62, 3.59, -1.42]} rotation={[0, 0, -Math.PI / 2]} scale={[0.25, 3.98, 0.25]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials['steel.001']} position={[-63.62, 3.59, -10.77]} rotation={[0, 0, -Math.PI / 2]} scale={[0.25, 3.98, 0.25]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['steel.001']} position={[-59.73, -0.13, -1.42]} rotation={[0, 0, -Math.PI]} scale={[0.28, 4.51, 0.28]} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials['steel.001']} position={[-59.73, -0.13, -10.77]} rotation={[0, 0, -Math.PI]} scale={[0.28, 4.51, 0.28]} />
      <mesh geometry={nodes.Plane015.geometry} material={materials['Material.006']} position={[-76.26, 0.21, -6.7]} scale={-21.84} />
      <mesh geometry={nodes.Plane014.geometry} material={materials['Material.006']} position={[-61.23, 0.36, -6.15]} scale={[-6.3, -5.07, -5.07]} />
      <mesh geometry={nodes.Plane010.geometry} material={materials['Material.002']} position={[-65.81, 20.35, 2.2]} rotation={[Math.PI / 2, 0, -1.14]} scale={1.38} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.002']} position={[-64.53, 22.27, -0.48]} rotation={[Math.PI / 2, 0, -1.14]} scale={1.38} />
      <mesh geometry={nodes.Plane007.geometry} material={materials['Material.002']} position={[-63.62, 22.27, -11.18]} rotation={[Math.PI / 2, 0, -1.69]} scale={1.38} />
      <mesh geometry={nodes.Plane008.geometry} material={materials['Material.002']} position={[-64.1, 20.35, -14.68]} rotation={[Math.PI / 2, 0, -1.7]} scale={1.38} />
      <mesh geometry={nodes.Plane003.geometry} material={materials['Transparent glass.001']} position={[-32.1, 0.59, -123.57]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Plane006.geometry} material={materials['Transparent glass.001']} position={[-32.02, 0.59, 105.07]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Plane004.geometry} material={materials['Transparent glass.001']} position={[105.34, 1.18, 13.83]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1, 1, 2.13]} />
      <mesh geometry={nodes.Plane005.geometry} material={materials['Transparent glass.001']} position={[-114.59, 1.18, 14.19]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1, 1, 2.14]} />
      <mesh geometry={nodes.path2085.geometry} material={materials['SVGMat.007']} position={[-62.48, 15.83, -7.54]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={212.04} />
      <mesh geometry={nodes.path2102.geometry} material={materials['SVGMat.010']} position={[-63.39, 25.99, -5.92]} rotation={[1.57, 0, -1.58]} scale={125.76} />
      <mesh geometry={nodes.path2115.geometry} material={materials['SVGMat.012']} position={[-62.07, 18.79, -42.76]} rotation={[Math.PI / 2, 0.01, -Math.PI / 2]} scale={195.23} />
      <mesh geometry={nodes.Circle.geometry} material={materials['Material.020']} position={[-63.09, 13.05, -35.14]} rotation={[0, 0, -Math.PI / 2]} scale={1.25} />
      <mesh geometry={nodes.Circle001.geometry} material={materials['Material.020']} position={[-63.09, 13.05, -49.99]} rotation={[0, 0, -Math.PI / 2]} scale={1.25} />
      <mesh geometry={nodes.Circle002.geometry} material={materials['Material.020']} position={[-63.09, 13.05, -42.49]} rotation={[0, 0, -Math.PI / 2]} scale={1.25} />
      <mesh geometry={nodes.Circle006.geometry} material={materials['Material.020']} position={[-63.09, 6.21, -35.23]} rotation={[0, 0, -Math.PI / 2]} scale={1.25} />
      <mesh geometry={nodes.Circle007.geometry} material={materials['Material.020']} position={[-63.09, 6.21, -49.93]} rotation={[0, 0, -Math.PI / 2]} scale={1.25} />
      <mesh geometry={nodes.Circle008.geometry} material={materials['Material.020']} position={[-89.86, 14.05, -32.27]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={1.99} />
      <mesh geometry={nodes.Circle009.geometry} material={materials['Material.020']} position={[-79.8, 14.05, -32.27]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={1.99} />
      <mesh geometry={nodes.Circle010.geometry} material={materials['Material.020']} position={[-69.29, 14.05, -32.27]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={1.99} />
      <mesh geometry={nodes.Circle011.geometry} material={materials['Material.020']} position={[-89.5, 6.02, -32.27]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={1.99} />
      <mesh geometry={nodes.Circle012.geometry} material={materials['Material.020']} position={[-79.45, 6.02, -32.27]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={1.99} />
      <mesh geometry={nodes.Circle013.geometry} material={materials['Material.020']} position={[-68.94, 6.02, -32.27]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={1.99} />
      <mesh geometry={nodes.Circle014.geometry} material={materials['Material.020']} position={[-68.41, 14.05, -52.31]} rotation={[0, 1.56, -1.57]} scale={1.99} />
      <mesh geometry={nodes.Circle015.geometry} material={materials['Material.020']} position={[-78.46, 14.05, -52.41]} rotation={[0, 1.56, -1.57]} scale={1.99} />
      <mesh geometry={nodes.Circle016.geometry} material={materials['Material.020']} position={[-88.97, 14.05, -52.52]} rotation={[0, 1.56, -1.57]} scale={1.99} />
      <mesh geometry={nodes.Circle017.geometry} material={materials['Material.020']} position={[-68.76, 6.02, -52.32]} rotation={[0, 1.56, -1.57]} scale={1.99} />
      <mesh geometry={nodes.Circle018.geometry} material={materials['Material.020']} position={[-78.82, 6.02, -52.42]} rotation={[0, 1.56, -1.57]} scale={1.99} />
      <mesh geometry={nodes.Circle019.geometry} material={materials['Material.020']} position={[-89.33, 6.02, -52.52]} rotation={[0, 1.56, -1.57]} scale={1.99} />
      <mesh geometry={nodes.city_sample_houses_1011.geometry} material={materials['Material.021']} position={[-63.13, 12.42, -49.97]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.city_sample_houses_1009.geometry} material={materials['Material.021']} position={[-63.13, 12.42, -42.48]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.city_sample_houses_1024.geometry} material={materials['Material.021']} position={[-63.13, 5.57, -35.22]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.city_sample_houses_1008.geometry} material={materials['Material.021']} position={[-63.13, 5.57, -49.92]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.city_sample_houses_1007.geometry} material={materials['Material.021']} position={[-63.13, 12.42, -35.12]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.city_sample_houses_1029.geometry} material={materials['Material.021']} position={[-89.89, 13.04, -32.32]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.02, 0.02, 0.01]} />
      <mesh geometry={nodes.city_sample_houses_1030.geometry} material={materials['Material.021']} position={[-79.83, 13.04, -32.32]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.02, 0.02, 0.01]} />
      <mesh geometry={nodes.city_sample_houses_1031.geometry} material={materials['Material.021']} position={[-69.32, 13.04, -32.32]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.02, 0.02, 0.01]} />
      <mesh geometry={nodes.city_sample_houses_1033.geometry} material={materials['Material.021']} position={[-89.53, 5.02, -32.32]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.02, 0.02, 0.01]} />
      <mesh geometry={nodes.city_sample_houses_1005.geometry} material={materials['Material.021']} position={[-79.47, 5.02, -32.32]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.02, 0.02, 0.01]} />
      <mesh geometry={nodes.city_sample_houses_1001.geometry} material={materials['Material.021']} position={[-68.96, 5.02, -32.32]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.02, 0.02, 0.01]} />
      <mesh geometry={nodes.city_sample_houses_1036.geometry} material={materials['Material.021']} position={[-68.38, 13.04, -52.26]} rotation={[Math.PI / 2, 0, 1.58]} scale={[0.02, 0.02, 0.01]} />
      <mesh geometry={nodes.city_sample_houses_1037.geometry} material={materials['Material.021']} position={[-78.44, 13.04, -52.36]} rotation={[Math.PI / 2, 0, 1.58]} scale={[0.02, 0.02, 0.01]} />
      <mesh geometry={nodes.city_sample_houses_1038.geometry} material={materials['Material.021']} position={[-88.94, 13.04, -52.46]} rotation={[Math.PI / 2, 0, 1.58]} scale={[0.02, 0.02, 0.01]} />
      <mesh geometry={nodes.city_sample_houses_1039.geometry} material={materials['Material.021']} position={[-68.74, 5.02, -52.26]} rotation={[Math.PI / 2, 0, 1.58]} scale={[0.02, 0.02, 0.01]} />
      <mesh geometry={nodes.city_sample_houses_1040.geometry} material={materials['Material.021']} position={[-78.79, 5.02, -52.36]} rotation={[Math.PI / 2, 0, 1.58]} scale={[0.02, 0.02, 0.01]} />
      <mesh geometry={nodes.city_sample_houses_1041.geometry} material={materials['Material.021']} position={[-89.3, 5.02, -52.47]} rotation={[Math.PI / 2, 0, 1.58]} scale={[0.02, 0.02, 0.01]} />
      <mesh geometry={nodes.city_sample_houses_1027.geometry} material={materials['Material.023']} position={[-61.83, 4.26, -42.47]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Cube009.geometry} material={materials['Material.020']} position={[-79.66, 8.44, -42.4]} scale={[16.5, 8.67, 9.73]} />
      <mesh geometry={nodes.Cube020.geometry} material={materials['Material.020']} position={[-61.46, 8.36, -42.48]} scale={[0.58, 0.5, 2.47]} />
      <mesh geometry={nodes.Cube021.geometry} material={materials['default']} position={[-61.46, 9.17, -42.42]} scale={[0.76, 0.58, 0.65]} />
      <mesh geometry={nodes.Cube022.geometry} material={materials['Material.020']} position={[-61.46, 7.64, -40.43]} scale={[0.58, 0.21, 0.47]} />
      <mesh geometry={nodes.Cube023.geometry} material={materials['Material.020']} position={[-61.46, 7.64, -44.42]} scale={[0.58, 0.21, 0.47]} />
      <mesh geometry={nodes.Cube024.geometry} material={materials['Material.020']} position={[-61.46, 4.83, -40.36]} rotation={[Math.PI / 2, 0, 0]} scale={[0.22, 0.21, 2.66]} />
      <mesh geometry={nodes.Cube025.geometry} material={materials['Material.020']} position={[-61.46, 4.83, -44.51]} rotation={[Math.PI / 2, 0, 0]} scale={[0.22, 0.21, 2.66]} />
      <mesh geometry={nodes.Cube026.geometry} material={materials['Material.020']} position={[-61.3, 0.9, -42.43]} scale={[0.58, 0.58, 0.54]} />
      <mesh geometry={nodes.Cube027.geometry} material={materials['Material.020']} position={[-89.86, 12.81, -32.29]} rotation={[0, -Math.PI / 2, 0]} scale={[0.92, 0.08, 1.65]} />
      <mesh geometry={nodes.Cube030.geometry} material={materials['Material.020']} position={[-63.1, 12.27, -49.99]} scale={[0.58, 0.05, 1.04]} />
      <mesh geometry={nodes.Cube031.geometry} material={materials['Material.020']} position={[-63.1, 12.27, -42.5]} scale={[0.58, 0.05, 1.04]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.020']} position={[-63.1, 12.27, -35.14]} scale={[0.58, 0.05, 1.04]} />
      <mesh geometry={nodes.Cube033.geometry} material={materials['Material.020']} position={[-63.1, 5.43, -35.24]} scale={[0.58, 0.05, 1.04]} />
      <mesh geometry={nodes.Cube034.geometry} material={materials['Material.020']} position={[-63.1, 5.43, -49.93]} scale={[0.58, 0.05, 1.04]} />
      <mesh geometry={nodes.Cube035.geometry} material={materials['Material.020']} position={[-79.8, 12.81, -32.29]} rotation={[0, -Math.PI / 2, 0]} scale={[0.92, 0.08, 1.65]} />
      <mesh geometry={nodes.Cube036.geometry} material={materials['Material.020']} position={[-69.29, 12.81, -32.29]} rotation={[0, -Math.PI / 2, 0]} scale={[0.92, 0.08, 1.65]} />
      <mesh geometry={nodes.Cube037.geometry} material={materials['Material.020']} position={[-89.5, 4.79, -32.29]} rotation={[0, -Math.PI / 2, 0]} scale={[0.92, 0.08, 1.65]} />
      <mesh geometry={nodes.Cube038.geometry} material={materials['Material.020']} position={[-79.44, 4.79, -32.29]} rotation={[0, -Math.PI / 2, 0]} scale={[0.92, 0.08, 1.65]} />
      <mesh geometry={nodes.Cube039.geometry} material={materials['Material.020']} position={[-68.93, 4.79, -32.29]} rotation={[0, -Math.PI / 2, 0]} scale={[0.92, 0.08, 1.65]} />
      <mesh geometry={nodes.Cube040.geometry} material={materials['Material.020']} position={[-68.41, 12.81, -52.3]} rotation={[0, 1.56, 0]} scale={[0.92, 0.08, 1.65]} />
      <mesh geometry={nodes.Cube041.geometry} material={materials['Material.020']} position={[-78.46, 12.81, -52.4]} rotation={[0, 1.56, 0]} scale={[0.92, 0.08, 1.65]} />
      <mesh geometry={nodes.Cube042.geometry} material={materials['Material.020']} position={[-88.97, 12.81, -52.5]} rotation={[0, 1.56, 0]} scale={[0.92, 0.08, 1.65]} />
      <mesh geometry={nodes.Cube043.geometry} material={materials['Material.020']} position={[-68.77, 4.79, -52.3]} rotation={[0, 1.56, 0]} scale={[0.92, 0.08, 1.65]} />
      <mesh geometry={nodes.Cube044.geometry} material={materials['Material.020']} position={[-78.82, 4.79, -52.4]} rotation={[0, 1.56, 0]} scale={[0.92, 0.08, 1.65]} />
      <mesh geometry={nodes.Cube045.geometry} material={materials['Material.020']} position={[-89.33, 4.79, -52.5]} rotation={[0, 1.56, 0]} scale={[0.92, 0.08, 1.65]} />
      <mesh geometry={nodes.Cube046.geometry} material={materials['Material.020']} position={[-73.25, 19.09, -42.6]} scale={0.58} />
      <mesh geometry={nodes.Cube049.geometry} material={materials['Material.020']} position={[-58.29, 0.28, -42.44]} scale={[0.78, 0.58, 0.17]} />
      <mesh geometry={nodes.Cylinder006.geometry} material={materials['Material.020']} position={[-61.96, 9.48, -38.46]} scale={[0.58, 0.43, 0.58]} />
      <mesh geometry={nodes.Cylinder007.geometry} material={materials['Material.020']} position={[-61.96, 9.48, -46.39]} scale={[0.58, 0.43, 0.58]} />
      <mesh geometry={nodes.Plane013.geometry} material={materials['Material.022']} position={[-78.33, -0.41, -42.33]} scale={[-21.89, -14.66, -14.66]} />
    </group>
  )
}

useGLTF.preload('/invactCity.gltf')
