/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/assets/Player.gltf')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    props.animation === 'wave' && actions.handRaise.fadeIn(0.8).play();
    props.animation === 'walk' && actions.walk.play();
    props.animation === 'sit' && actions.sit.play(); 
    return () => {
        actions.handRaise.stop();
        actions.walk.stop();
        actions.sit.stop();
    }
  }, [props.animation]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group  
          position={[0.0, 0, -60]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={2.0}
        >
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh geometry={nodes.mesh.geometry} material={materials.Material} skeleton={nodes.mesh.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Player.gltf')
