/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/assets/Player.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group  
          position={[0.0, 0, -60]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={2.0}
        >
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh geometry={nodes.mesh.geometry} material={materials.Material} skeleton={nodes.mesh.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Player.gltf')
